
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: >
      sh -c "python src/drf_recipe_api/manage.py runserver 0.0.0.0:8000"