[project]
name = "drf-recipe-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sajad Hatami", email = "sajadhatamiw@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=5.2,<5.3",
    "django-filter>=26.1",
    "djangorestframework>=3.18.1",
    "markdown>=3.10.3",
]

[project.scripts]
drf-recipe-api = "drf_recipe_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
]
